swagger: '2.0'
info:
  description: A Simple IP Address API
  title: new
  version: v1
host: api.ipify.org
schemes:
  - https
basePath: /
paths:
  /cloudlink/rest/api-docs:
    get:
      summary: Get client IP
      responses:
        '200':
          description: Success response
  /test:
    post:
      summary: Get client new
      operationId: testNew
      responses:
        '200':
          description: Success response
  /users:
    get:
      summary: new api
      responses: {}
      operationId: get-users
      description: Success response
